#!/bin/bash
#author: thetrier
#Version 1.0

 filesize=filesize.txt
 fileloc=`pwd`
 
 if [[ $EUID -ne 0 ]]
 	then
		echo "Hello $USER. To get files from all location this must be run as root. Please use su or sudo $0" 1>&2
         	exit 100
		
 else [[ $EUID -eq 0 ]]
 	echo -n "Please input file type separated by space: "
 	echo "(eq.: *.tar.gz *.zip *.bz2)"
	read -a fltp
	echo -n "Please insert minimum file's size: "
	echo "(eq. 10k 300M)
	read min
	echo "Please insert maximum size of the file: "
 	echo "(eq. 100k 300M)"
 	read max
 
 	for file in "${fltp[@]}"; do find / -name "$file" -type f -size +$min -a -size -$max -exec ls -1alh 2>/dev/null {} \; | awk '{{
    print $5 "         " $9}' | tee $filesize;done;
 
 fi
  
 echo "Your file is located in $fileloc and is called $filesize"
 exit 0

